name: CustomLobby
version: 1.0
author: Mayus, Tallerik
main: customlobby.CustomLobby
commands:
    ban:
        description: Bannt einen Spieler.
    warn:
        description: Verwarnt einen Spieler.